# Generated by Django 4.2.11 on 2026-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sk_id_curr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
