# Generated by Django 4.2.11 on 2026-06-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_application_sk_id_curr"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="shap_values",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
