# Generated by Django 4.2.11 on 2026-06-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ml_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='api.mlmodel'),
        ),
    ]
