from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=150, unique=True) # Login
    email = models.EmailField(unique=True)
    sk_id_curr = models.IntegerField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

class Application(models.Model): # Creates a table of loan applications
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications') # Each application belongs to one user
    amt_income = models.DecimalField(max_digits=15, decimal_places=2)
    amt_credit = models.DecimalField(max_digits=15, decimal_places=2)
    currency = models.CharField(max_length=10, default='RUB')
    probability = models.FloatField(null=True, blank=True)
    risk_label = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"App #{self.id} - User {self.user.email} ({self.risk_label})"

from django.db import models

class ClientFeature(models.Model):
    # Unique client ID from the dataset (Primary Key)
    sk_id_curr = models.IntegerField(unique=True, primary_key=True, db_index=True)

    class Meta:
        verbose_name = "Client Feature"
        verbose_name_plural = "Client Features"

    def __str__(self):
        return f"Client {self.sk_id_curr}"

# Full list of features
RAW_FEATURES = [
    'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 
    'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 
    'NAME_FAMILY_STATUS', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 
    'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 
    'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 
    'REG_REGION_NOT_LIVE_REGION', 'REG_CITY_NOT_LIVE_CITY', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 
    'EXT_SOURCE_3', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 
    'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 
    'NONLIVINGAREA_AVG', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 
    'LIVINGAPARTMENTS_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'BASEMENTAREA_MEDI', 
    'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ENTRANCES_MEDI', 
    'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 
    'NONLIVINGAPARTMENTS_MEDI', 'HOUSETYPE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 
    'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_3', 
    'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_18', 
    'AMT_REQ_CREDIT_BUREAU_YEAR', 'DAYS_EMPLOYED_ANOM', 'EXT_SOURCE_1_WAS_MISSING', 
    'EXT_SOURCE_3_WAS_MISSING', 'CREDIT_ANNUITY_RATIO', 'CREDIT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO', 
    'CREDIT_INCOME_PERCENT', 'ANNUITY_INCOME_PERCENT', 'CREDIT_TERM', 'DAYS_EMPLOYED_PERCENT', 
    'CREDIT_GOODS_RATIO', 'EXT_SOURCES_MEAN', 'EXT_SOURCES_PROD', 'EXT_SOURCES_STD', 
    'EMPLOYED_TO_BIRTH_RATIO', 'CAR_TO_BIRTH_RATIO', 'PHONE_TO_BIRTH_RATIO', 'BURO_DAYS_CREDIT_MEAN', 
    'BURO_DAYS_CREDIT_MAX', 'BURO_DAYS_CREDIT_VAR', 'BURO_AMT_CREDIT_SUM_DEBT_MAX', 
    'BURO_AMT_CREDIT_SUM_DEBT_SUM', 'BURO_CREDIT_ACTIVE_Active_MEAN', 'BURO_CREDIT_ACTIVE_Closed_MEAN', 
    'BURO_CREDIT_ACTIVE_Sold_MEAN', 'BURO_CREDIT_TYPE_Another type of loan_MEAN', 
    'BURO_CREDIT_TYPE_Car loan_MEAN', 'BURO_CREDIT_TYPE_Consumer credit_MEAN', 
    'BURO_CREDIT_TYPE_Credit card_MEAN', 'BURO_CREDIT_TYPE_Loan for business development_MEAN', 
    'BURO_CREDIT_TYPE_Loan for working capital replenishment_MEAN', 'BURO_CREDIT_TYPE_Microloan_MEAN', 
    'BURO_CREDIT_TYPE_Mortgage_MEAN', 'BURO_CREDIT_TYPE_Other_MEAN', 'BURO_CREDIT_TYPE_Unknown type of loan_MEAN', 
    'BURO_LAST_ACTIVE_DAYS_CREDIT_MAX', 'PREV_AMT_ANNUITY_MEAN', 'PREV_AMT_APPLICATION_MEAN', 
    'PREV_AMT_APPLICATION_MAX', 'PREV_AMT_CREDIT_MEAN', 'PREV_AMT_CREDIT_MAX', 'PREV_AMT_GOODS_PRICE_MEAN', 
    'PREV_AMT_GOODS_PRICE_MAX', 'PREV_RATE_DOWN_PAYMENT_MEAN', 'PREV_RATE_DOWN_PAYMENT_MAX', 
    'PREV_DAYS_DECISION_MEAN', 'PREV_CNT_PAYMENT_MEAN', 'PREV_CNT_PAYMENT_SUM', 
    'PREV_ASKED_AMT_ID_CURR_DIFF_MEAN', 'PREV_DOWNPAYMENT_CREDIT_RATIO_MEAN', 'PREV_ANNUITY_CREDIT_RATIO_MEAN', 
    'PREV_ANNUITY_CREDIT_RATIO_MAX', 'PREV_NAME_CONTRACT_TYPE_Revolving loans_MEAN', 
    'PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN', 'PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN', 
    'PREV_NAME_CONTRACT_STATUS_Approved_MEAN', 'PREV_NAME_CONTRACT_STATUS_Canceled_MEAN', 
    'PREV_NAME_CONTRACT_STATUS_Refused_MEAN', 'PREV_CODE_REJECT_REASON_HC_MEAN', 
    'PREV_CODE_REJECT_REASON_LIMIT_MEAN', 'PREV_CODE_REJECT_REASON_SCO_MEAN', 'PREV_CODE_REJECT_REASON_VERIF_MEAN', 
    'PREV_CODE_REJECT_REASON_XAP_MEAN', 'PREV_CODE_REJECT_REASON_XNA_MEAN', 'PREV_NAME_CLIENT_TYPE_New_MEAN', 
    'PREV_NAME_GOODS_CATEGORY_XNA_MEAN', 'PREV_NAME_PORTFOLIO_Cards_MEAN', 'PREV_NAME_PORTFOLIO_XNA_MEAN', 
    'PREV_NAME_PRODUCT_TYPE_walk-in_MEAN', 'PREV_CHANNEL_TYPE_Car dealer_MEAN', 
    'PREV_CHANNEL_TYPE_Channel of corporate sales_MEAN', 'PREV_CHANNEL_TYPE_Stone_MEAN', 
    'PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN', 'PREV_NAME_SELLER_INDUSTRY_XNA_MEAN', 
    'PREV_NAME_YIELD_GROUP_high_MEAN', 'PREV_NAME_YIELD_GROUP_low_action_MEAN', 
    'PREV_PRODUCT_COMBINATION_Card Street_MEAN', 'PREV_PRODUCT_COMBINATION_Card X-Sell_MEAN', 
    'PREV_PRODUCT_COMBINATION_Cash_MEAN', 'PREV_PRODUCT_COMBINATION_Cash Street: high_MEAN', 
    'PREV_PRODUCT_COMBINATION_Cash X-Sell: low_MEAN', 'PREV_PRODUCT_COMBINATION_POS household with interest_MEAN', 
    'PREV_PRODUCT_COMBINATION_POS household without interest_MEAN', 'PREV_LAST_NAME_CONTRACT_STATUS_Canceled', 
    'PREV_LAST_PRODUCT_COMBINATION_Card Street', 'PREV_LAST_PRODUCT_COMBINATION_Card X-Sell', 
    'PREV_LAST_PRODUCT_COMBINATION_Cash', 'INS_DBD_MAX', 'INS_DBD_MEAN', 'INS_PAYMENT_DIFF_MAX', 
    'INS_PAYMENT_DIFF_MEAN', 'INS_PAYMENT_DIFF_SUM', 'INS_PAYMENT_DIFF_VAR', 'INS_AMT_INSTALMENT_MAX', 
    'INS_AMT_INSTALMENT_MEAN', 'INS_AMT_INSTALMENT_SUM', 'INS_AMT_PAYMENT_MAX', 'INS_AMT_PAYMENT_MEAN', 
    'INS_AMT_PAYMENT_SUM', 'INS_DAYS_ENTRY_PAYMENT_MAX', 'INS_DAYS_ENTRY_PAYMENT_MEAN', 
    'INS_DAYS_ENTRY_PAYMENT_SUM', 'INS_COUNT', 'INS_365_DPD_SUM', 'POS_MONTHS_BALANCE_SIZE', 
    'POS_SK_DPD_MEAN', 'POS_SK_DPD_DEF_MAX', 'POS_SK_DPD_DEF_MEAN', 'POS_NAME_CONTRACT_STATUS_Active_MEAN', 
    'POS_NAME_CONTRACT_STATUS_Amortized debt_MEAN', 'POS_NAME_CONTRACT_STATUS_Approved_MEAN', 
    'POS_NAME_CONTRACT_STATUS_Completed_MEAN', 'POS_NAME_CONTRACT_STATUS_Demand_MEAN', 
    'POS_NAME_CONTRACT_STATUS_Returned to the store_MEAN', 'POS_NAME_CONTRACT_STATUS_Signed_MEAN', 
    'POS_ACTIVE_COUNT', 'CC_MONTHS_BALANCE_MIN', 'CC_MONTHS_BALANCE_MEAN', 'CC_MONTHS_BALANCE_SUM', 
    'CC_MONTHS_BALANCE_VAR', 'CC_AMT_BALANCE_MIN', 'CC_AMT_BALANCE_MAX', 'CC_AMT_BALANCE_MEAN', 
    'CC_AMT_BALANCE_SUM', 'CC_AMT_BALANCE_VAR', 'CC_AMT_CREDIT_LIMIT_ACTUAL_MIN', 
    'CC_AMT_CREDIT_LIMIT_ACTUAL_MEAN', 'CC_AMT_CREDIT_LIMIT_ACTUAL_VAR', 'CC_AMT_DRAWINGS_ATM_CURRENT_MIN', 
    'CC_AMT_DRAWINGS_ATM_CURRENT_MEAN', 'CC_AMT_DRAWINGS_ATM_CURRENT_SUM', 'CC_AMT_DRAWINGS_CURRENT_MIN', 
    'CC_AMT_DRAWINGS_CURRENT_MEAN', 'CC_AMT_DRAWINGS_CURRENT_VAR', 'CC_AMT_DRAWINGS_POS_CURRENT_MAX', 
    'CC_AMT_DRAWINGS_POS_CURRENT_MEAN', 'CC_AMT_DRAWINGS_POS_CURRENT_SUM', 'CC_AMT_DRAWINGS_POS_CURRENT_VAR', 
    'CC_AMT_INST_MIN_REGULARITY_MEAN', 'CC_AMT_INST_MIN_REGULARITY_SUM', 'CC_AMT_INST_MIN_REGULARITY_VAR', 
    'CC_AMT_PAYMENT_CURRENT_MAX', 'CC_AMT_PAYMENT_CURRENT_MEAN', 'CC_AMT_PAYMENT_CURRENT_SUM', 
    'CC_AMT_PAYMENT_CURRENT_VAR', 'CC_AMT_PAYMENT_TOTAL_CURRENT_MIN', 'CC_AMT_PAYMENT_TOTAL_CURRENT_MAX', 
    'CC_AMT_PAYMENT_TOTAL_CURRENT_MEAN', 'CC_AMT_PAYMENT_TOTAL_CURRENT_SUM', 'CC_AMT_PAYMENT_TOTAL_CURRENT_VAR', 
    'CC_AMT_RECEIVABLE_PRINCIPAL_MIN', 'CC_AMT_RECEIVABLE_PRINCIPAL_MAX', 'CC_AMT_RECEIVABLE_PRINCIPAL_MEAN', 
    'CC_AMT_RECEIVABLE_PRINCIPAL_SUM', 'CC_AMT_RECEIVABLE_PRINCIPAL_VAR', 'CC_AMT_RECIVABLE_MIN', 
    'CC_AMT_RECIVABLE_MAX', 'CC_AMT_RECIVABLE_MEAN', 'CC_AMT_RECIVABLE_SUM', 'CC_AMT_RECIVABLE_VAR', 
    'CC_AMT_TOTAL_RECEIVABLE_MIN', 'CC_AMT_TOTAL_RECEIVABLE_MAX', 'CC_AMT_TOTAL_RECEIVABLE_MEAN', 
    'CC_AMT_TOTAL_RECEIVABLE_SUM', 'CC_AMT_TOTAL_RECEIVABLE_VAR', 'CC_CNT_DRAWINGS_ATM_CURRENT_MIN', 
    'CC_CNT_DRAWINGS_ATM_CURRENT_MEAN', 'CC_CNT_DRAWINGS_ATM_CURRENT_SUM', 'CC_CNT_DRAWINGS_ATM_CURRENT_VAR', 
    'CC_CNT_DRAWINGS_CURRENT_MAX', 'CC_CNT_DRAWINGS_CURRENT_MEAN', 'CC_CNT_DRAWINGS_CURRENT_SUM', 
    'CC_CNT_DRAWINGS_OTHER_CURRENT_SUM', 'CC_CNT_DRAWINGS_POS_CURRENT_MAX', 'CC_CNT_DRAWINGS_POS_CURRENT_MEAN', 
    'CC_CNT_DRAWINGS_POS_CURRENT_SUM', 'CC_CNT_DRAWINGS_POS_CURRENT_VAR', 'CC_CNT_INSTALMENT_MATURE_CUM_MAX', 
    'CC_CNT_INSTALMENT_MATURE_CUM_MEAN', 'CC_CNT_INSTALMENT_MATURE_CUM_SUM', 'CC_SK_DPD_MAX', 
    'CC_SK_DPD_MEAN', 'CC_SK_DPD_DEF_MEAN', 'CC_SK_DPD_DEF_SUM', 'CC_SK_DPD_DEF_VAR'
]

# Dynamically create fields in Django during class loading
for feature in RAW_FEATURES:
    # Clear the name of special characters and FORCEDLY collapse '__' into '_'
    sanitized_field = feature.lower().replace(' ', '_').replace(':', '_').replace('-', '_').replace('__', '_')
    ClientFeature.add_to_class(sanitized_field, models.FloatField(null=True, blank=True))