"""
Django settings for loan_sight project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# List of domains from which the server can be accessed
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [ # List of Django applications
    'django.contrib.admin', # Admin panel
    'django.contrib.auth', # Users and Auth
    'django.contrib.contenttypes', # Working with model types
    'django.contrib.sessions', # Users sessions
    'django.contrib.messages', # Notifications system
    'django.contrib.staticfiles', # CSS, JS, Images
]

MIDDLEWARE = [ # Intermediate request handlers
    'django.middleware.security.SecurityMiddleware', # Additional website protection
    'django.contrib.sessions.middleware.SessionMiddleware', # Working with sessions
    'django.middleware.common.CommonMiddleware', # General improvements to query handling
    'django.middleware.csrf.CsrfViewMiddleware', # Protection against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Defines the current user
    'django.contrib.messages.middleware.MessageMiddleware', # Message system
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Protection against clickjacking attacks
]

ROOT_URLCONF = 'loan_sight.urls'

TEMPLATES = [ # Django HTML Template Settings
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loan_sight.wsgi.application' # Entry point for web server (Gunicorn, uWSGI)

# Database Configuration
# Supports both DATABASE_URL and individual environment variables
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL (postgresql://user:password@host:port/dbname)
    import dj_database_url # Library that automatically parses URLs
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Use individual environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'loansight'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [ # Check the strength of passwords
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True # Support for internationalization
USE_TZ = True # Store time taking into account time zones

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'